import './globals.css'
import type { Metadata } from 'next'

import { Roboto } from 'next/font/google'

import { Modal } from '@/components/modal'
import { ModalProvider } from '@/contexts/modal.context'
import { FloattingButton } from '@/components/floatting-button'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className={`${roboto.className} min-h-screen w-screen`}>
        <ModalProvider>
          {children}
          {/* <Navbar /> */}
          <Modal />
          <FloattingButton />
        </ModalProvider>
      </body>
    </html>
  )
}
